import type { Metadata } from "next";
import { Factory, GraduationCap, HeartPulse, Landmark, PackageCheck, ScanSearch, ServerCog } from "lucide-react";
import { CtaBand, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/MarketingPrimitives";

export const metadata: Metadata = { title: "Industries", description: "Illustrative AI applications across healthcare, manufacturing, finance, retail, education, logistics, and technology." };
const industries = [
  [HeartPulse,"Healthcare","Explore responsible analytics, patient-risk signals, document intelligence, and workflow support.",["Clinical and operational analytics","Healthcare NLP","Decision-support workflows"]],
  [Factory,"Manufacturing","Use operational data for quality intelligence, forecasting, and maintenance prioritization.",["Predictive maintenance","Quality inspection","Production forecasting"]],
  [Landmark,"Finance","Apply AI to risk patterns, customer intelligence, document workflows, and financial sentiment.",["Fraud and risk signals","Customer analytics","Document intelligence"]],
  [ScanSearch,"Retail","Understand demand and customer behavior to support merchandising and experience decisions.",["Customer segmentation","Demand forecasting","Recommendation workflows"]],
  [GraduationCap,"Education","Support personalized learning, knowledge access, learner analytics, and institutional enablement.",["Learning support","Knowledge assistants","AI upskilling"]],
  [PackageCheck,"Logistics","Improve planning and visibility with forecasting, anomaly detection, and operational analytics.",["Demand and route signals","Exception analysis","Capacity planning"]],
  [ServerCog,"SaaS & Technology","Embed AI into products, customer operations, knowledge systems, and internal workflows.",["Product copilots","Support intelligence","Agentic workflows"]],
] as const;
export default function IndustriesPage() { return <main><PageHero eyebrow="Industry applications" title="AI grounded in" accent="real operating contexts." description="Explore practical, illustrative use cases mapped to the decisions, data, and workflows that matter across industries." /><section className="mk-section mk-section-alt"><div className="mk-container"><SectionHeading kicker="Across sectors" title="From insight to applied intelligence." description="These examples describe potential solution areas—not invented client claims or guaranteed outcomes." /><div className="mk-card-grid">{industries.map(([Icon,title,description,items]) => <FeatureCard key={title} icon={Icon} title={title} description={description} items={[...items]} />)}</div></div></section><section className="mk-section"><div className="mk-container"><SectionHeading kicker="Practical approach" title="Start with the workflow, not the trend." description="Industry AI becomes useful when it is grounded in a clear decision, trustworthy data, and the people responsible for the outcome." /><div className="mk-process">{[["01","Context","Understand the operating environment and users."],["02","Data","Assess availability, quality, access, and constraints."],["03","Solution","Select an appropriate AI and workflow approach."],["04","Adoption","Validate, enable users, and improve responsibly."]].map(([n,title,text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><CtaBand title="Explore an AI opportunity in your industry." /></main>; }
