"use client";
import { useMemo, useState } from "react";
import { CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import EDAService from "@/services/eda.service";
import type { EDAChartResult, EDAColumn, RelationshipRequest } from "@/types/eda";
export default function EDARelationships({ projectId, columns }: { projectId: string; columns: EDAColumn[] }) {
  const numeric = useMemo(() => columns.filter((item) => item.semantic_type === "numeric"), [columns]); const categories = useMemo(() => columns.filter((item) => ["categorical", "boolean", "text"].includes(item.semantic_type)), [columns]); const dates = useMemo(() => columns.filter((item) => item.semantic_type === "datetime"), [columns]);
  const [kind, setKind] = useState<RelationshipRequest["kind"]>("correlation"); const [method, setMethod] = useState<"pearson" | "spearman">("pearson"); const [x, setX] = useState(""); const [y, setY] = useState(""); const [category, setCategory] = useState(""); const [result, setResult] = useState<EDAChartResult | null>(null); const [error, setError] = useState("");
  const run = async () => { setError(""); try { setResult(await EDAService.relationships(projectId, { kind, method, x: x || numeric[0]?.name || categories[0]?.name, y: y || numeric[1]?.name || categories[1]?.name, numeric: y || numeric[0]?.name, category: category || categories[0]?.name, datetime_column: x || dates[0]?.name })); } catch (err) { const value = err as { response?: { data?: { message?: string } } }; setError(value.response?.data?.message ?? "Relationship analysis failed."); } };
  return <div className="space-y-5"><div className="grid gap-3 rounded-xl border border-slate-800 bg-slate-950 p-4 md:grid-cols-5"><label className="text-xs text-slate-400">Analysis<select value={kind} onChange={(e) => { setKind(e.target.value as RelationshipRequest["kind"]); setResult(null); }} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-2 text-white"><option value="correlation">Correlation heatmap</option><option value="scatter">Scatter plot</option><option value="crosstab">Cross-tabulation</option><option value="grouped_distribution">Grouped distribution</option><option value="grouped_aggregation">Grouped aggregation</option><option value="datetime_trend">Datetime trend</option></select></label>{kind === "correlation" && <label className="text-xs text-slate-400">Method<select value={method} onChange={(e) => setMethod(e.target.value as typeof method)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-2 text-white"><option>pearson</option><option>spearman</option></select></label>}{kind === "scatter" && <><Select label="X numeric" value={x} onChange={setX} items={numeric} /><Select label="Y numeric" value={y} onChange={setY} items={numeric} /></>}{kind === "crosstab" && <><Select label="First category" value={x} onChange={setX} items={categories} /><Select label="Second category" value={y} onChange={setY} items={categories} /></>}{["grouped_distribution", "grouped_aggregation"].includes(kind) && <><Select label="Category" value={category} onChange={setCategory} items={categories} /><Select label="Numeric" value={y} onChange={setY} items={numeric} /></>}{kind === "datetime_trend" && <><Select label="Datetime" value={x} onChange={setX} items={dates} /><Select label="Numeric" value={y} onChange={setY} items={numeric} /></>}<button onClick={() => void run()} className="self-end rounded-lg bg-blue-600 px-4 py-2 font-medium text-white">Analyze</button></div>{error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{result?.kind === "correlation" && result.matrix && <Heatmap result={result} />}{result?.kind === "scatter" && result.data && <div className="h-[420px] rounded-xl border border-slate-800 bg-slate-950 p-4"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#253047" /><XAxis dataKey="x" name="X" stroke="#94a3b8" /><YAxis dataKey="y" name="Y" stroke="#94a3b8" /><Tooltip cursor={{ strokeDasharray: "3 3" }} /><Scatter data={result.data} fill="#3b82f6" /></ScatterChart></ResponsiveContainer><p className="text-xs text-slate-400">{result.sampled ? `Deterministic sample: ${result.sampled_rows} of ${result.total_rows} rows.` : "All valid points shown."}</p></div>}{result && !["correlation", "scatter"].includes(result.kind) && <pre className="max-h-[450px] overflow-auto rounded-xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-300">{JSON.stringify(result, null, 2)}</pre>}</div>;
}
function Select({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: EDAColumn[] }) { return <label className="text-xs text-slate-400">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-2 text-white"><option value="">Select…</option>{items.map((item) => <option key={item.name}>{item.name}</option>)}</select></label>; }
function Heatmap({ result }: { result: EDAChartResult }) { return <div className="overflow-auto rounded-xl border border-slate-800 bg-slate-950 p-4"><table className="text-xs"><thead><tr><th /><>{result.columns?.map((item) => <th key={item} className="p-2 text-slate-400">{item}</th>)}</></tr></thead><tbody>{result.matrix?.map((row, index) => <tr key={result.columns?.[index]}><th className="p-2 text-left text-slate-400">{result.columns?.[index]}</th>{row.map((value, cell) => <td key={cell} className="p-3 text-center text-white" style={{ backgroundColor: value == null ? "#1e293b" : `rgba(${value < 0 ? "239,68,68" : "59,130,246"},${Math.abs(value)})` }}>{value == null ? "—" : value.toFixed(2)}</td>)}</tr>)}</tbody></table></div>; }
