"use client";
import { useEffect, useState } from "react";
import { AlertCircle, BarChart3, Columns3, FileText, GitBranch, LayoutDashboard, Loader2, ShieldCheck, WandSparkles } from "lucide-react";
import useEDA from "@/hooks/useEDA";
import type { EDAProject } from "@/types/eda";
import EDAColumns from "./EDAColumns"; import EDAExplorer from "./EDAExplorer"; import EDAOverview from "./EDAOverview"; import EDAQuality from "./EDAQuality"; import EDAReport from "./EDAReport"; import EDARelationships from "./EDARelationships"; import EDATransform from "./EDATransform"; import EDAUpload from "./EDAUpload"; import EDAVisualize from "./EDAVisualize";
type Tab = "overview" | "columns" | "quality" | "visualize" | "relationships" | "transform" | "report";
const tabs: Array<{ id: Tab; label: string; icon: React.ElementType }> = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "columns", label: "Columns", icon: Columns3 }, { id: "quality", label: "Data Quality", icon: ShieldCheck }, { id: "visualize", label: "Visualize", icon: BarChart3 }, { id: "relationships", label: "Relationships", icon: GitBranch }, { id: "transform", label: "Transform", icon: WandSparkles }, { id: "report", label: "Report", icon: FileText }];
export default function EDAWorkspace() {
  const eda = useEDA(); const [tab, setTab] = useState<Tab>("overview");
  const { loadProfiles, loadQuality } = eda;
  useEffect(() => { if (tab === "columns") void loadProfiles(); if (tab === "quality") void loadQuality(); }, [tab, loadProfiles, loadQuality]);
  const choose = (project: EDAProject) => { setTab("overview"); void eda.select(project); };
  const remove = (project: EDAProject) => { if (window.confirm(`Delete the EDA project “${project.original_filename}”? The source will be moved to recoverable trash.`)) void eda.remove(project); };
  const derived = async (project: EDAProject) => { await eda.loadCatalog(1, eda.search); choose(project); };
  return <div className="grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]"><aside className="space-y-4"><EDAUpload uploading={eda.uploading} onUpload={eda.upload} /><EDAExplorer catalog={eda.catalog} selected={eda.selected} search={eda.search} loading={eda.loadingCatalog} onSearch={eda.setSearch} onPage={eda.setPage} onRefresh={() => void eda.loadCatalog()} onSelect={choose} onDelete={remove} /></aside><main className="min-w-0 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto border-b border-slate-800" role="tablist" aria-label="EDA workflow">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} role="tab" aria-selected={tab === item.id} disabled={!eda.selected} onClick={() => setTab(item.id)} className={`inline-flex items-center gap-2 border-b-2 px-4 py-4 text-sm font-medium disabled:opacity-40 ${tab === item.id ? "border-blue-500 text-blue-300" : "border-transparent text-slate-400 hover:text-white"}`}><Icon size={16} />{item.label}</button>; })}</div>{eda.error && <div className="m-5 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300"><AlertCircle size={18} />{eda.error}</div>}<div className="relative p-5 lg:p-7">{eda.loadingProject && <div className="absolute inset-0 z-30 flex items-center justify-center bg-slate-900/80"><Loader2 className="animate-spin text-blue-400" /></div>}{!eda.selected && <div className="py-28 text-center"><LayoutDashboard className="mx-auto text-slate-700" size={52} /><h2 className="mt-4 text-xl font-semibold text-white">Start an EDA workflow</h2><p className="mt-2 text-slate-400">Upload tabular data or select an existing EDA project.</p></div>}{eda.selected && eda.overview && eda.preview && <>{tab === "overview" && <EDAOverview overview={eda.overview} preview={eda.preview} onPreviewPage={(page) => void eda.changePreviewPage(page)} />}{tab === "columns" && <EDAColumns data={eda.profiles} />}{tab === "quality" && <EDAQuality data={eda.quality} />}{tab === "visualize" && <EDAVisualize projectId={eda.selected.id} columns={eda.overview.columns} />}{tab === "relationships" && <EDARelationships projectId={eda.selected.id} columns={eda.overview.columns} />}{tab === "transform" && <EDATransform project={eda.selected} columns={eda.overview.columns} onCreated={(project) => void derived(project)} />}{tab === "report" && <EDAReport project={eda.selected} />}</>}</div></main></div>;
}
