import Link from "next/link";
import type { Metadata } from "next";
import { Blocks, BriefcaseBusiness, Building2, Check, Code2, GraduationCap, Route, Users } from "lucide-react";
import { CtaBand, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/MarketingPrimitives";

export const metadata: Metadata = { title: "AI Training", description: "Practical AI learning pathways for students, professionals, technical teams, and organizations." };
const programs = [
  { title:"AI Foundations", audience:"Students, fresh graduates, and career switchers", outcome:"Build strong foundations, train first models, and create an introductory RAG application.", modules:["Introduction to AI","Foundations of ML","LLMs & RAG basics","Hands-on projects"] },
  { title:"AI Engineering", audience:"Learners ready to build real-world AI applications", outcome:"Develop deeper model-building skills and solve applied industry problems.", modules:["Advanced machine learning","LLM fine-tuning","Production AI systems","Real-world case studies"] },
  { title:"Enterprise AI & Agentic Systems", audience:"AI engineers, working professionals, and technical architects", outcome:"Design and manage enterprise-scale AI workflows and intelligent agent systems.", modules:["Enterprise AI architecture","Agentic systems design","Multi-agent orchestration","Production deployment"] },
  { title:"AI for Organizations", audience:"Organizations, universities, leadership, and corporate teams", outcome:"Develop practical AI capability across teams and support responsible adoption.", modules:["AI strategy & roadmap","Team capability building","Responsible AI","Change management"] },
];
export default function TrainingPage() { return <main><PageHero eyebrow="AI training & upskilling" title="Learn AI by" accent="building with it." description="Structured, hands-on learning pathways designed for beginners to experienced professionals." /><section className="pb-12"><div className="mk-container"><Link className="mk-button-primary" href="/register">Register for training or a demo</Link></div></section><section className="mk-section"><div className="mk-container"><SectionHeading kicker="Our programs" title="Flexible learning pathways." description="Structured programs designed to fit your needs and goals." /><div className="grid grid-cols-1 gap-8 md:grid-cols-2">{programs.map(program => <FeatureCard key={program.title} icon={GraduationCap} eyebrow={program.audience} title={program.title} description={program.outcome} items={program.modules} />)}</div></div></section>
  <section id="curriculum" className="mk-section"><div className="mk-container"><SectionHeading kicker="Curriculum" title="Concepts become working systems." description="The curriculum retains core concepts while building hands-on skills." /><div className="grid grid-cols-1 gap-6 md:grid-cols-3">{[{icon: Code2, title: "Learn by Building", description: "Every concept is reinforced through real-world projects and applications."}, {icon: Users, title: "Expert Instruction", description: "Learn from industry practitioners and AI specialists with proven track records."}, {icon: Blocks, title: "Modular Design", description: "Build skills progressively with flexible, modular learning components."}].map(item => <FeatureCard key={item.title} icon={item.icon} title={item.title} description={item.description} />)}</div></div></section>
  <section id="projects" className="mk-section mk-section-alt"><div className="mk-container"><SectionHeading kicker="Learning experience" title="Practical by design." description="Learning combines structured modules, real projects, mentoring, and community." /><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">{[{icon: Code2, title: "Structured Modules"}, {icon: Route, title: "Industry Projects"}, {icon: BriefcaseBusiness, title: "Expert Mentoring"}, {icon: Building2, title: "Community Access"}].map(item => <FeatureCard key={item.title} icon={item.icon} title={item.title} description="Build practical skills with real-world application." />)}</div></div></section>
  <CtaBand title="Ready to upskill your team?" description="Connect with our team to discuss your training needs." />
</main>;
}
