import Link from "next/link";
import type { Metadata } from "next";
import { Blocks, BriefcaseBusiness, Building2, Check, Code2, GraduationCap, Route, Users } from "lucide-react";
import { CtaBand, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/MarketingPrimitives";

export const metadata: Metadata = { title: "AI Training", description: "Practical AI learning pathways for students, professionals, technical teams, and organizations." };
const programs = [
  { title:"AI Foundations", audience:"Students, fresh graduates, and career switchers", outcome:"Build strong foundations, train first models, and create an introductory RAG application.", modules:["Python fundamentals","SQL for data science","Machine learning fundamentals","Introduction to LLMs","Introduction to RAG"] },
  { title:"AI Engineering", audience:"Learners ready to build real-world AI applications", outcome:"Develop deeper model-building skills and solve applied industry problems.", modules:["Advanced machine learning","Deep learning","Neural networks","Natural language processing","Industry case studies"] },
  { title:"Enterprise AI & Agentic Systems", audience:"AI engineers, working professionals, and technical architects", outcome:"Design and manage enterprise-scale AI workflows and intelligent agents.", modules:["MLOps","AIOps","Agentic AI frameworks","Governance","Guardrails","Enterprise deployment"] },
  { title:"AI for Organizations", audience:"Organizations, universities, leadership, and corporate teams", outcome:"Develop practical AI capability across teams and support responsible adoption.", modules:["Executive AI awareness","Prompt engineering","AI productivity","Generative AI","Custom AI solutions","AI governance"] },
];
export default function TrainingPage() { return <main><PageHero eyebrow="AI training & upskilling" title="Learn AI by" accent="building with it." description="Structured, hands-on learning pathways that connect concepts, real tools, datasets, projects, mentorship, and industry context." />
  <section className="pb-12"><div className="mk-container"><Link className="mk-button-primary" href="/training/register">Register for training or a demo</Link></div></section><section className="mk-section mk-section-alt"><div className="mk-container"><SectionHeading kicker="Programs" title="A pathway for every stage of the AI journey." description="Choose a learning path aligned to your starting point, role, and intended outcome." /><div className="mt-14 grid gap-5 lg:grid-cols-2">{programs.map((program,index) => <article key={program.title} className="rounded-3xl border border-white/[.08] bg-[#090f1e] p-7 md:p-9"><div className="flex items-center justify-between"><span className="font-mono text-xs text-slate-600">0{index+1}</span><GraduationCap size={20} className="text-cyan-300" /></div><h2 className="mt-8 text-2xl font-semibold">{program.title}</h2><p className="mt-2 text-sm text-cyan-200">{program.audience}</p><p className="mt-4 text-sm leading-6 text-slate-400">{program.outcome}</p><div className="mk-pill-row">{program.modules.map(module => <span className="mk-pill" key={module}>{module}</span>)}</div></article>)}</div></div></section>
  <section id="curriculum" className="mk-section"><div className="mk-container"><SectionHeading kicker="Curriculum" title="Concepts become working systems." description="The curriculum retains core foundations while progressing into advanced modeling, GenAI, agentic systems, governance, and deployment." /><div className="mk-card-grid mk-four">{[[Code2,"Core foundations","Python, SQL, data preparation, statistics, and machine learning."],[Blocks,"Applied AI","Deep learning, NLP, LLMs, RAG, analytics, and practical case work."],[Route,"Enterprise systems","MLOps, AIOps, deployment, governance, guardrails, and agents."],[BriefcaseBusiness,"Industry readiness","Challenge labs, portfolio projects, communication, and solution thinking."]].map(([Icon,title,description]) => <FeatureCard key={String(title)} icon={Icon as typeof Code2} title={String(title)} description={String(description)} />)}</div></div></section>
  <section id="projects" className="mk-section mk-section-alt"><div className="mk-container"><SectionHeading kicker="Learning experience" title="Practical by design." description="Learning combines guided instruction with Studio-based experimentation, projects, feedback, and application." /><div className="mk-card-grid mk-four">{[[Users,"Live and guided","Instructor-led guidance, discussion, review, and mentorship."],[Code2,"Hands-on labs","Practice with SQL, Python, EDA, model training, NLP, DL, and GenAI."],[BriefcaseBusiness,"Applied projects","Work through realistic datasets and business-oriented challenge statements."],[Building2,"Flexible delivery","Pathways for individual learners, universities, and corporate teams."]].map(([Icon,title,description]) => <FeatureCard key={String(title)} icon={Icon as typeof Users} title={String(title)} description={String(description)} />)}</div><div className="mt-14 grid gap-8 rounded-3xl border border-white/[.08] bg-[#090f1e] p-8 lg:grid-cols-2 lg:p-11"><div><p className="mk-kicker">Learning journey</p><h3 className="mt-4 text-3xl font-semibold tracking-[-.04em]">Learn → Build → Practice → Deploy</h3><p className="mt-4 text-slate-400">Progress from guided fundamentals to applied projects and industry-ready solution thinking.</p></div><div className="grid grid-cols-2 gap-3">{["Students","Fresh graduates","Career switchers","Working professionals","Technical teams","Organizations"].map(profile => <div key={profile} className="flex items-center gap-2 rounded-xl border border-white/[.07] p-3 text-sm text-slate-300"><Check size={14} className="text-cyan-300" />{profile}</div>)}</div></div></div></section><CtaBand title="Find the right AI learning pathway." description="Talk with our team about individual learning, university programs, or organization-wide AI upskilling." /></main>; }
